//  Normally I would fetch these names
//  from the api but there is no straightworward
//  route to access all names so I took a portion
//  of names just to demonstrate how the search suggestion should work.

export const characterNames = [
  "Rick Sanchez",
  "Morty Smith",
  "Summer Smith",
  "Beth Smith",
  "Jerry Smith",
  "Abradolf Lincler",
  "Adjudicator Rick",
  "Agency Director",
  "Alan Rails",
  "Albert Einstein",
  "Alexander",
  "Annie",
  "Antenna Morty",
  "Antenna Rick",
  "Ants in my Eyes Johnson",
  "Aqua Morty",
  "Aqua Rick",
  "Artist Morty",
  "Attila Starwar",
  "Baby Legs",
  "Abadango Cluster Princess",
  "Alien Googah",
  "Alien Morty",
  "Alien Rick",
  "Amish Cyborg",
  "Arcade Alien",
  "Armagheadon",
  "Arthricia",
  "Baby Wizard",
  "Bearded Lady",
  "Beebo",
  "Bepisian",
  "Beta-Seven",
  "Birdperson",
  "Blamph",
  "Blim Blam",
  "Blue Diplomat",
  "Boobloosian",
  "Borpocian",
];
